# Generated by Django 4.1.4 on 2023-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('stu_id', models.IntegerField(default='')),
                ('place', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
